### PR TITLE
Add function for "Residual sum of squares"

### PR DESCRIPTION
**Pull request by Domenico-Esposito**
I have add the function for calculate the "Residual sum of squares" (https://en.wikipedia.org/wiki/Residual_sum_of_squares).

### CODE REVIEW

**Comment by paescebu** [comment]
@Domenico-Esposito  I like it! Thanks for the contribution! Gives a nice option to validate the output of the regression.
Wondering if it would make more sense to add just a few more tests to cover special cases such as empty arrays of points and coefficients, what do you think?

Just to see if those cases are covered as well by the method.

**Review by paescebu — APPROVED** [review]

**Comment by Domenico-Esposito** [comment]
Yes, is a good idea!

**Comment by paescebu** [comment]
Merged! Thanks for your contribution :) 
Next cool thing would be to calculate R^2, to have a normalized idea about the quality of the regression! :D

**Comment by Domenico-Esposito** [comment]
> Merged! Thanks for your contribution :) 

Great!

> Next cool thing would be to calculate R^2, to have a normalized idea about the quality of the regression! :D

Another good idea! :)
I'll try to implement it!

---

_Link to definition: https://en.wikipedia.org/wiki/Coefficient_of_determination#Definitions_

**Comment by paescebu** [comment]
Hehe, was the next logical step i guess :) 
Go wild! Happy for any contribution that makes this package more useful for other mathematicians and engineers :)

**Pull request merged**
